import { createPagesEventContext } from 'cloudflare:test'

const cfMock: IncomingRequestCfProperties<unknown> = {
  colo: 'LAX',
  country: 'US',
  region: 'CA',
  city: 'Los Angeles',
  latitude: '34.0522',
  longitude: '-118.2437',
  postalCode: '90001',
  metroCode: '803',
  timezone: 'America/Los_Angeles',
  asn: 12345,
  organization: 'Example Org',
  edgeRequestKeepAliveStatus: 0,
  httpProtocol: 'HTTP/2',
  requestPriority: 'high',
  tlsVersion: 'TLSv1.3',
  tlsCipher: 'ECDHE-RSA-AES128-GCM-SHA256',
  botManagement: {
    verifiedBot: true,
    corporateProxy: false,
    staticResource: false,
    detectionIds: [0],
    score: 95,
    ja3Hash: 'example-ja3-hash',
  },
  clientTrustScore: 100,
  tlsClientAuth: {
    certPresented: '0',
    certVerified: 'NONE',
    certRevoked: '0',
    certIssuerDN: '',
    certSubjectDN: '',
    certIssuerDNRFC2253: '',
    certSubjectDNRFC2253: '',
    certIssuerDNLegacy: '',
    certSubjectDNLegacy: '',
    certSerial: '',
    certIssuerSerial: '',
    certSKI: '',
    certIssuerSKI: '',
    certFingerprintSHA1: '',
    certFingerprintSHA256: '',
    certNotBefore: '',
    certNotAfter: '',
  },
}

export default function getContext<
  P extends string,
  T extends { [key in P]: string } | undefined = undefined
>(rawRequest: Request, params?: T) {
  // vitest loads dom lib, because of that typeescript takes Request/RequestInfo types over
  // those generated by wrangler in types.d.ts, which are the real ones used in Cloudflare Workers envs
  // const cfRequest = request as unknown as Request<unknown, IncomingRequestCfProperties>
  // cfRequest.cf = cfMock
  const request = new Request(rawRequest, {
    cf: cfMock,
  }) as Request<unknown, IncomingRequestCfProperties<unknown>>

  const ctx = createPagesEventContext({
    request,
    params: params || {},
    data: undefined, // data passed between request(pass request to next layer of workers/rules etc.)
  })

  return ctx as unknown as EventContext<Env, T extends undefined ? never : P, never>
}
