import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import Navigation from '@/components/Navigation'
import './globals.css'
import InitializeData from '@/components/InitializeData'

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable}`}>
        <InitializeData />
        <div className="page">{children}</div>
        <Navigation />
      </body>
    </html>
  )
}
