import '@total-typescript/ts-reset'
import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './order.css'
import './reset.css'
import './spaces.css'
import './theme.css'
import './utilities.css'
import './components.css'
import './elements.css'
import InitializeData from '@/components/InitializeData/InitializeData'
import GlobalErrors from '@/components/GlobalErrors/GlobalErrors'
import Navigation from '@/components/Navigation/Navigation'

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable}`}>
        <InitializeData />
        <div className="page">
          {children}
          <Navigation />
        </div>
        <GlobalErrors />
      </body>
    </html>
  )
}
