#!/usr/bin/env node

/**
 * Script to compare build sizes between two builds
 * This is typically used in CI to compare PR builds against the base branch
 * 
 * Usage:
 *   node scripts/compare-size.cjs <base-analysis.json> <current-analysis.json>
 * 
 * The analysis JSON files should be generated by analyze-size.cjs
 */

const fs = require('fs');
const path = require('path');

/**
 * Format bytes to human readable format
 */
function formatBytes(bytes) {
  const absBytes = Math.abs(bytes);
  if (absBytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(absBytes) / Math.log(k));
  const formatted = parseFloat((absBytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  return bytes < 0 ? '-' + formatted : formatted;
}

/**
 * Format difference with color and sign
 */
function formatDiff(diff, percentage) {
  const sign = diff > 0 ? '+' : '';
  const emoji = diff > 0 ? '📈' : diff < 0 ? '📉' : '➖';
  return `${emoji} ${sign}${formatBytes(diff)} (${sign}${percentage.toFixed(2)}%)`;
}

/**
 * Create a mapping of files based on their logical names (without hashes)
 * This helps compare files even when their hash changes
 */
function normalizeFileName(fileName) {
  // Remove hash patterns from Next.js build files
  // Examples:
  //   _next/static/chunks/framework-abc123.js -> _next/static/chunks/framework-[hash].js
  //   _next/static/css/app-def456.css -> _next/static/css/app-[hash].css
  //   _next/static/chunks/123-abc-def.js -> _next/static/chunks/123-[hash]-[hash].js
  
  // For files in _next/static/chunks or _next/static/css, remove the hash part
  if (fileName.includes('_next/static/chunks/') || fileName.includes('_next/static/css/')) {
    // Match common Next.js hash patterns: -abc123def, _abc123, etc.
    return fileName.replace(/[-_][a-zA-Z0-9]{6,}/g, '-[hash]');
  }
  
  return fileName;
}

/**
 * Main comparison function
 */
function compareSize(baseFile, currentFile) {
  // Read analysis files
  if (!fs.existsSync(baseFile)) {
    console.error(`Error: Base analysis file '${baseFile}' not found.`);
    process.exit(1);
  }

  if (!fs.existsSync(currentFile)) {
    console.error(`Error: Current analysis file '${currentFile}' not found.`);
    process.exit(1);
  }

  const baseAnalysis = JSON.parse(fs.readFileSync(baseFile, 'utf8'));
  const currentAnalysis = JSON.parse(fs.readFileSync(currentFile, 'utf8'));

  console.log('📊 Build Size Comparison Report\n');
  console.log(`Base build:    ${new Date(baseAnalysis.timestamp).toLocaleString()}`);
  console.log(`Current build: ${new Date(currentAnalysis.timestamp).toLocaleString()}\n`);

  // Compare total sizes
  const totalDiff = currentAnalysis.totalSize - baseAnalysis.totalSize;
  const totalPercentage = (totalDiff / baseAnalysis.totalSize) * 100;

  console.log('Overall Size Change:');
  console.log('━'.repeat(70));
  console.log(`Base:    ${formatBytes(baseAnalysis.totalSize)}`);
  console.log(`Current: ${formatBytes(currentAnalysis.totalSize)}`);
  console.log(`Change:  ${formatDiff(totalDiff, totalPercentage)}`);
  console.log('');

  // Create normalized file maps
  const baseFileMap = new Map();
  const currentFileMap = new Map();

  baseAnalysis.files.forEach(file => {
    const normalizedName = normalizeFileName(file.path);
    if (!baseFileMap.has(normalizedName)) {
      baseFileMap.set(normalizedName, []);
    }
    baseFileMap.get(normalizedName).push(file);
  });

  currentAnalysis.files.forEach(file => {
    const normalizedName = normalizeFileName(file.path);
    if (!currentFileMap.has(normalizedName)) {
      currentFileMap.set(normalizedName, []);
    }
    currentFileMap.get(normalizedName).push(file);
  });

  // Find changed files
  const changes = [];
  
  // Compare files that exist in both builds
  for (const [normalizedName, baseFiles] of baseFileMap.entries()) {
    const currentFiles = currentFileMap.get(normalizedName) || [];
    
    // For normalized files, sum up the sizes
    const baseSize = baseFiles.reduce((sum, f) => sum + f.size, 0);
    const currentSize = currentFiles.reduce((sum, f) => sum + f.size, 0);
    
    if (currentSize !== baseSize) {
      const diff = currentSize - baseSize;
      const percentage = baseSize > 0 ? (diff / baseSize) * 100 : 100;
      
      changes.push({
        file: normalizedName,
        baseSize,
        currentSize,
        diff,
        percentage,
        type: currentSize === 0 ? 'removed' : 'changed',
      });
    }
  }

  // Find new files
  for (const [normalizedName, currentFiles] of currentFileMap.entries()) {
    if (!baseFileMap.has(normalizedName)) {
      const currentSize = currentFiles.reduce((sum, f) => sum + f.size, 0);
      changes.push({
        file: normalizedName,
        baseSize: 0,
        currentSize,
        diff: currentSize,
        percentage: 100,
        type: 'added',
      });
    }
  }

  // Sort changes by absolute diff size
  changes.sort((a, b) => Math.abs(b.diff) - Math.abs(a.diff));

  // Display changes
  if (changes.length > 0) {
    console.log('File Changes (Top 30):');
    console.log('━'.repeat(70));
    
    const displayChanges = changes.slice(0, 30);
    for (const change of displayChanges) {
      const typeLabel = change.type === 'added' ? '🆕 NEW' : 
                        change.type === 'removed' ? '❌ REMOVED' :
                        change.diff > 0 ? '📈 GREW' : '📉 SHRUNK';
      
      console.log(`\n${typeLabel.padEnd(12)} ${change.file}`);
      if (change.type !== 'added') {
        console.log(`  Base:    ${formatBytes(change.baseSize)}`);
      }
      if (change.type !== 'removed') {
        console.log(`  Current: ${formatBytes(change.currentSize)}`);
      }
      console.log(`  Change:  ${formatDiff(change.diff, change.percentage)}`);
    }

    if (changes.length > 30) {
      console.log(`\n... and ${changes.length - 30} more changes`);
    }
  } else {
    console.log('No file size changes detected! ✨');
  }

  console.log('\n' + '━'.repeat(70));

  // Summary statistics
  const added = changes.filter(c => c.type === 'added').length;
  const removed = changes.filter(c => c.type === 'removed').length;
  const modified = changes.filter(c => c.type === 'changed').length;

  console.log('\nSummary:');
  console.log(`  Total changes: ${changes.length}`);
  console.log(`  Added files:   ${added}`);
  console.log(`  Removed files: ${removed}`);
  console.log(`  Modified files: ${modified}`);

  // Exit with non-zero if size increased significantly
  if (totalPercentage > 5) {
    console.log('\n⚠️  WARNING: Build size increased by more than 5%!');
    process.exit(1);
  } else if (totalDiff > 0) {
    console.log('\n✅ Build size increased slightly.');
  } else if (totalDiff < 0) {
    console.log('\n🎉 Build size decreased!');
  } else {
    console.log('\n✅ Build size unchanged.');
  }
}

// Parse command line arguments
const args = process.argv.slice(2);

if (args.length !== 2) {
  console.error('Usage: node scripts/compare-size.cjs <base-analysis.json> <current-analysis.json>');
  process.exit(1);
}

const [baseFile, currentFile] = args;
compareSize(baseFile, currentFile);
